-- Latest-only short-positioning snapshot for local/API/Neon use.
-- Full history remains exclusively in public.us_equities_short_analytics locally.
CREATE TABLE IF NOT EXISTS public.us_equities_short_analytics_latest (
    ticker text PRIMARY KEY,
    name text,
    security_type text NOT NULL DEFAULT 'unknown',
    sector text,
    industry text,
    exchange text,
    analytics_date date NOT NULL,
    latest_short_volume_date date NOT NULL,
    latest_si_settlement_date date,
    latest_si_publication_date date,
    short_volume numeric,
    short_exempt_volume numeric,
    total_finra_volume numeric,
    short_volume_ratio numeric,
    short_exempt_ratio numeric,
    short_exempt_share_of_short numeric,
    svr_5d numeric,
    svr_20d numeric,
    svr_60d numeric,
    svr_z20 numeric,
    svr_z60 numeric,
    svr_pctile_5d numeric,
    svr_pctile_20d numeric,
    svr_pctile_60d numeric,
    casv_5d numeric,
    casv_10d numeric,
    casv_20d numeric,
    svr_acceleration_5_20 numeric,
    svr_acceleration_20_60 numeric,
    short_activity_persistence numeric,
    short_interest numeric,
    previous_short_interest numeric,
    si_change_latest numeric,
    si_change_pct_latest numeric,
    short_pct_float numeric,
    days_to_cover numeric,
    si_observation_count integer,
    si_change_1obs numeric,
    si_change_2obs numeric,
    si_change_4obs numeric,
    si_change_8obs numeric,
    si_change_12obs numeric,
    si_slope_6m numeric,
    si_slope_12m numeric,
    si_r2_6m numeric,
    si_r2_12m numeric,
    si_acceleration numeric,
    si_acceleration_state text,
    si_persistence_6m numeric,
    si_persistence_12m numeric,
    si_persistence_24m numeric,
    si_volatility_6m numeric,
    si_volatility_12m numeric,
    own_si_percentile_1y numeric,
    own_si_percentile_3y numeric,
    own_si_percentile_5y numeric,
    market_si_percentile numeric,
    sector_si_percentile numeric,
    industry_si_percentile numeric,
    latest_price numeric,
    rel_return_1m numeric,
    rel_return_3m numeric,
    rel_return_6m numeric,
    rel_return_12m numeric,
    up_capture numeric,
    down_capture numeric,
    long_short_asymmetry numeric,
    short_pressure_effectiveness numeric,
    dollar_adv20 numeric,
    dollar_adv60 numeric,
    volatility_20d numeric,
    volatility_60d numeric,
    ma20 numeric,
    ma50 numeric,
    ma100 numeric,
    ma200 numeric,
    price_vs_ma20_pct numeric,
    price_vs_ma50_pct numeric,
    price_vs_ma100_pct numeric,
    price_vs_ma200_pct numeric,
    ma20_slope numeric,
    ma50_slope numeric,
    ma100_slope numeric,
    ma200_slope numeric,
    trend_structure text,
    rsi14 numeric,
    rsi_state text,
    macd numeric,
    macd_signal numeric,
    macd_histogram numeric,
    macd_state text,
    expected_si_direction text,
    p_si_increase numeric,
    p_si_flat numeric,
    p_si_decrease numeric,
    flow_confirmation_signal text,
    short_position_score numeric,
    short_activity_score numeric,
    short_flow_confirmation_score numeric,
    funding_short_score numeric,
    funding_short_quality_score numeric,
    unwind_risk_score numeric,
    short_regime text,
    regime_confidence numeric,
    regime_reason_json jsonb,
    data_quality_status text,
    data_quality_score numeric,
    source_hash text NOT NULL,
    source_calculated_at timestamptz,
    snapshot_updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_short_latest_regime_scores
    ON public.us_equities_short_analytics_latest
    (security_type, short_regime, funding_short_score DESC, funding_short_quality_score DESC);
CREATE INDEX IF NOT EXISTS idx_short_latest_sector
    ON public.us_equities_short_analytics_latest (sector, industry);
CREATE INDEX IF NOT EXISTS idx_short_latest_analytics_date
    ON public.us_equities_short_analytics_latest (analytics_date DESC);
