@echo off
call "C:\Users\User\anaconda3\Scripts\activate.bat"
call conda activate PostgreSQL_db
cd /d "C:\Users\User\OneDrive\Coding\DB_builder"

powershell -NoProfile -ExecutionPolicy Bypass -Command ^
  "$ErrorActionPreference = 'Stop';" ^
  "$Root = 'C:\Users\User\OneDrive\Coding\DB_builder';" ^
  "$Python = 'C:\Users\User\anaconda3\envs\PostgreSQL_db\python.exe';" ^
  "$LogDir = Join-Path $Root 'logs';" ^
  "New-Item -ItemType Directory -Force -Path $LogDir | Out-Null;" ^
  "$Stamp = Get-Date -Format 'yyyyMMdd_HHmmss';" ^
  "$Log = Join-Path $LogDir ('auto_postgreSQL_db_' + $Stamp + '.log');" ^
  "$IndicatorBatchSize = 400;" ^
  "function Write-Log($Level, $Message) { $Line = ('{0} [{1}] {2}' -f (Get-Date -Format 'yyyy-MM-dd HH:mm:ss'), $Level, $Message); Add-Content -LiteralPath $Log -Value $Line; Write-Host $Line }" ^
  "function Invoke-RetryPython($Script, $Name, [string[]]$ScriptArgs = @()) { for ($Attempt = 1; $Attempt -le 3; $Attempt++) { Write-Log 'START' ($Name + ' attempt ' + $Attempt); $ArgText = ((@($Script) + $ScriptArgs) -join ' '); $Psi = [System.Diagnostics.ProcessStartInfo]::new(); $Psi.FileName = $Python; $Psi.Arguments = $ArgText; $Psi.WorkingDirectory = $Root; $Psi.UseShellExecute = $false; $Psi.RedirectStandardOutput = $true; $Psi.RedirectStandardError = $true; $P = [System.Diagnostics.Process]::new(); $P.StartInfo = $Psi; [void]$P.Start(); $OutTask = $P.StandardOutput.ReadToEndAsync(); $ErrTask = $P.StandardError.ReadToEndAsync(); if (-not $P.WaitForExit(600000)) { $P.Kill(); $P.WaitForExit(); Write-Log 'TIMEOUT' ($Name + ' exceeded 600 seconds'); Add-Content -LiteralPath $Log -Value $OutTask.Result; Add-Content -LiteralPath $Log -Value $ErrTask.Result; if ($Attempt -lt 3) { Write-Log 'RETRY' ($Name + ' retrying after timeout in 60 seconds'); Start-Sleep -Seconds 60; continue }; return $false }; $P.WaitForExit(); Add-Content -LiteralPath $Log -Value $OutTask.Result; Add-Content -LiteralPath $Log -Value $ErrTask.Result; $ExitCode = $P.ExitCode; if ($ExitCode -eq 0) { Write-Log 'SUCCESS' $Name; return $true }; Write-Log 'ERROR' ($Name + ' exited with code ' + $ExitCode); if ($Attempt -lt 3) { Write-Log 'RETRY' ($Name + ' retrying after error in 60 seconds'); Start-Sleep -Seconds 60; continue }; return $false } }" ^
  "function Get-IndicatorTickers { $CodeB64 = 'aW1wb3J0IHN5czsgc3lzLnBhdGguaW5zZXJ0KDAsIHInQzpcVXNlcnNcVXNlclxPbmVEcml2ZVxDb2RpbmdcREJfYnVpbGRlclxzcmMnKTsgZnJvbSBkYl9idWlsZGVyLmNvbmZpZyBpbXBvcnQgbG9jYWxfZW5naW5lOyBmcm9tIHNxbGFsY2hlbXkgaW1wb3J0IHRleHQ7IGU9bG9jYWxfZW5naW5lKCk7IHE9J1NFTEVDVCByLnRpY2tlciBGUk9NIChTRUxFQ1QgdGlja2VyLCBNQVgoZGF0ZSkgbGF0ZXN0X3Jhd19kYXRlIEZST00gcHVibGljLnVzX2VxdWl0aWVzIEdST1VQIEJZIHRpY2tlcikgciBMRUZUIEpPSU4gKFNFTEVDVCB0aWNrZXIsIE1BWChkYXRlKSBsYXRlc3RfaW5kaWNhdG9yX2RhdGUgRlJPTSBwdWJsaWMudXNfZXF1aXRpZXNfaW5kaWNhdG9ycyBHUk9VUCBCWSB0aWNrZXIpIGkgT04gci50aWNrZXIgPSBpLnRpY2tlciBXSEVSRSBpLmxhdGVzdF9pbmRpY2F0b3JfZGF0ZSBJUyBOVUxMIE9SIHIubGF0ZXN0X3Jhd19kYXRlID4gaS5sYXRlc3RfaW5kaWNhdG9yX2RhdGUgT1JERVIgQlkgci50aWNrZXInOyBjPWUuY29ubmVjdCgpOyByb3dzPWMuZXhlY3V0ZSh0ZXh0KHEpKS5mZXRjaGFsbCgpOyBjLmNsb3NlKCk7IHByaW50KCdcbicuam9pbihyb3dbMF0gZm9yIHJvdyBpbiByb3dzKSk='; $Code = [Text.Encoding]::UTF8.GetString([Convert]::FromBase64String($CodeB64)); $Rows = & $Python -c $Code; if ($LASTEXITCODE -ne 0) { throw 'Failed to query indicator ticker backlog' }; @($Rows | Where-Object { $_ }) }" ^
  "function Invoke-IndicatorBatches { $BatchNumber = 0; $PreviousRemaining = $null; while ($true) { $Tickers = @(Get-IndicatorTickers); if ($Tickers.Count -eq 0) { Write-Log 'SUCCESS' 'pgSQL_equities_indicators.py no indicator backlog'; return $true }; if ($PreviousRemaining -ne $null -and $Tickers.Count -ge $PreviousRemaining) { Write-Log 'ERROR' ('pgSQL_equities_indicators.py made no backlog progress; remaining stayed at ' + $Tickers.Count); Write-Log 'ERROR' ('stuck tickers: ' + (($Tickers | Select-Object -First 25) -join ',')); return $false }; $PreviousRemaining = $Tickers.Count; $BatchNumber++; $Batch = @($Tickers | Select-Object -First $IndicatorBatchSize); $Csv = ($Batch -join ','); Write-Log 'START' ('pgSQL_equities_indicators.py batch ' + $BatchNumber + ' tickers ' + $Batch.Count + ' remaining ' + $Tickers.Count); if (-not (Invoke-RetryPython -Script 'scripts\pgSQL_equities_indicators.py' -Name ('pgSQL_equities_indicators.py batch ' + $BatchNumber) -ScriptArgs @('--tickers', $Csv, '--upsert-local'))) { return $false } } }" ^
  "Write-Log 'START' 'auto_postgreSQL_db workflow';" ^
  "if (-not (Invoke-RetryPython 'scripts\health_check.py' 'health_check.py')) { Write-Log 'ERROR' 'health_check.py failed after 3 retries'; exit 1 }" ^
  "if (-not (Invoke-RetryPython 'scripts\pgSQL_equities_auto.py' 'pgSQL_equities_auto.py')) { Write-Log 'ERROR' 'pgSQL_equities_auto.py failed after 3 retries'; exit 1 }" ^
  "if (-not (Invoke-IndicatorBatches)) { Write-Log 'ERROR' 'pgSQL_equities_indicators.py failed after 3 retries'; exit 1 }" ^
  "if (-not (Invoke-RetryPython 'scripts\pgSQL_daily_bulk_sync_to_neon.py' 'pgSQL_daily_bulk_sync_to_neon.py')) { Write-Log 'ERROR' 'pgSQL_daily_bulk_sync_to_neon.py failed after 3 retries'; exit 1 }" ^
  "Write-Log 'SUCCESS' 'auto_postgreSQL_db workflow complete'; exit 0"

exit /b %ERRORLEVEL%
